# Generated by Django 4.1 on 2022-08-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
