# Generated by Django 3.2.5 on 2021-09-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
