# Generated by Django 4.1 on 2022-08-23 12:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('orderId', models.CharField(max_length=200)),
                ('paymentInfo', models.CharField(blank=True, default='', max_length=200)),
                ('products', jsonfield.fields.JSONField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=6)),
                ('transactionid', models.CharField(blank=True, default='Not given', max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('status', models.CharField(default='Initiated', max_length=100)),
                ('deliveryStatus', models.CharField(default='unshipped', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('availableQty', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
